version: '3.9'

services:
  
  hackathon-python:
    env_file:
      - dev.env
    image: cnt/bidsvalidator
    volumes:
      - ./data:/service/data
    container_name: pennsieve-bidsvalidator
    build:
      context: .
      dockerfile: ./Dockerfile
